### ISSUE TITLE
White page on csv upload at client´s import

### ISSUE THREAD

**Issue by benhartwich** [invoiceninja/ui#2181]
Hi,

I get a white page when I try to import a csv at clients. /storage/log is empty, but there are errors at the browser console:

`bundle.722de2d2.js:56 TypeError: Cannot read properties of undefined (reading 'substring')
    at bundle.722de2d2.js:2745:3272
    at Array.map (<anonymous>)
    at OGe (bundle.722de2d2.js:2745:3100)
    at epe (bundle.722de2d2.js:54:19642)
    at Tie (bundle.722de2d2.js:56:3166)
    at k6e (bundle.722de2d2.js:56:45173)
    at E6e (bundle.722de2d2.js:56:40075)
    at egt (bundle.722de2d2.js:56:39998)
    at ZV (bundle.722de2d2.js:56:39847)
    at Fie (bundle.722de2d2.js:56:36177)
`

I could send an example csv privately.

**Comment by turbo124** [comment]
can you provide a redacted sample .csv please?

**Comment by benhartwich** [comment]
[contacts.csv](https://github.com/user-attachments/files/17716628/contacts.csv)
Please find attached.

**Comment by turbo124** [comment]
@benhartwich  ah, these have semi colons as the delimiter.

We'll add this to backlog for support. Whilst the backend support most delimiters the front ends only support comma separated.
